name: Deploy to Target Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform CLI (via dotnet tool)
      shell: pwsh
      run: |
        dotnet tool install --global Microsoft.PowerApps.CLI.Tool
        Add-Content -Path  -Value "C:\Users\Shivam Gupta\.dotnet\tools"

    - name: Run import.ps1 to deploy managed solution
      shell: pwsh
      run: ./pipelines/import.ps1

