name: Power Platform Solution Deployment

on:
  workflow_dispatch:

jobs:
  deploy-solution:
    runs-on: ubuntu-latest
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export Solution from Dev
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: https://orgca4ee91e.crm.dynamics.com/
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-name: DeploymentSolution
          solution-output-file: solutions/DeploymentSolution.zip

      - name: Import Solution to Target
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: https://orgc388d7c8.crm.dynamics.com/
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: solutions/DeploymentSolution.zip
          force-overwrite: true
          publish-changes: true
