name: Deploy to Target Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Power Platform CLI
      run: |
        iwr -useb https://aka.ms/pac -outfile pac-installer.ps1
        powershell -ExecutionPolicy Bypass -File pac-installer.ps1

    - name: Run import.ps1 to deploy managed solution
      shell: pwsh
      run: ./pipelines/import.ps1
